### ISSUE TITLE
Is there any idea how to upload .xls, .xlsx, and .csv files and reload data list without redirect page in submit?

### ISSUE THREAD

**Issue by tarek-aec** [axelpale/minimal-django-file-upload-example#9]

**Comment by axelpale** [comment]
Could you specify a bit, please? Do you mean how to upload files without page reload?

**Comment by tarek-aec** [comment]
yes, using jquery and ajax

**Comment by axelpale** [comment]
Uploading files asynchronously via AJAX is a complex topic thad did not have an easy answer at least a few years ago, before the HTML5 File API. Unfortunately the topic is out of the scope of this minimal file upload example. All I can say is that the async functionality does not require much additional code on server side, if any at all. This is more an issue of client side code. Nevertheless your question pushed me to think about having separate repository for that kind of introduction, though I cannot promise anything yet.

To give you something to work with here is a couple of resources you could look into:

A comprehensive discussion about the topic:
http://stackoverflow.com/questions/166221/how-can-i-upload-files-asynchronously

Working with File API:
http://www.html5rocks.com/en/tutorials/file/dndfiles/

I'll also close the issue because it is not directly related to the repository at hand.

I wish best luck to your coding!

**Comment by tarek-aec** [comment]
it is very usefull links thank you :+1:
